#
# 2007-2016 Cripto-Pay.com
#
# NOTICE OF LICENSE
#
# This source file is subject to the Open Software License (OSL 3.0)
# that is bundled with this package in the file LICENSE.txt.
# It is also available through the world-wide-web at this URL:
# https://opensource.org/licenses/OSL-3.0
# If you did not receive a copy of the license and are unable to
# obtain it through the world-wide-web, please send an email
# to support@cripto-pay.com so we can send you a copy immediately.
#
#  @author    CriptoPay SL <soporte@cripto-pay.com>
#  @copyright 2007-2016 CriptoPay SL
#  @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
#  @version 3.2
#  @source https://github.com/CriptoPay/CriptoPay_Prestashop

language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm
before_install:
    - composer self-update
install:
    - composer install
script: ./bin/phing -propertyfile build/travis.properties build-travis
cache:
    directories:
        - build/cache/
        - vendor/
matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

